import { Direction, Relationship, RelationshipsArray, Tags } from "./common"

export type BillStatus = "Pending" | "PendingReview" | "Rejected" | "Clearing" | "Sent" | "Canceled" | "Returned"

export interface Bill {
    /**
     * Identifier of the bill resource.
     */
    id: string

    /**
     * Type of the bill resource. The value is always bill.
     */
    type: "bill"

    /**
     * JSON object representing the bill data.
     */
    attributes: {
        /**
         * Date only. The date the resource was created.
         * RFC3339 format. For more information: https://en.wikipedia.org/wiki/ISO_8601#RFCs
         */
        createdAt: string

        /**
         * One of Pending, PendingReview, Rejected, Clearing, Sent, Canceled, Returned.
         */
        status: BillStatus

        /**
         * The direction in which the funds flow (either Debit or Credit).
         */
        direction: Direction

        /**
         * The amount (cents) of the bill.
         */
        amount: number

        /**
         * The description of the bill.
         */
        description: string

        /**
         * Optional. More information about the status.
         */
        reason?: string

        /**
         * See [Tags](https://developers.unit.co/#tags).
         */
        tags?: Tags
    }

    /**
     * Describes relationships between the bill resource and other resources.
     */
    relationships: {
        /**
         * The Deposit Account of the customer.
         */
        account: Relationship

        /**
         * The Customer the deposit account belongs to.
         * This relationship is only available if the account belongs to a single customer, business or individual.
         */
        customer?: Relationship

        /**
         * The list of Customers the deposit account belongs to.
         * This relationship is only available if the account belongs to multiple individual customers.
         */
        customers?: RelationshipsArray

        /**
         * The Transaction generated by this bill.
         */
        transaction?: Relationship
    }
}
